[project]
name = "BERT Python Torchscript"
version = "1.0.0"
description = "MAX Examples"
authors = ["Modular <hello@modular.com>"]
channels = ["pytorch", "conda-forge", "anaconda", "https://conda.modular.com/max/"]
platforms = ["osx-arm64","linux-64"]

[dependencies]
python = ">=3.11,<3.12"
max = ">=24.4.0dev6"
pip = ">=24.0,<25"
onnxruntime = "~=1.17.3"
pytorch = "~=2.2.2"
tritonclient = ">=2.44.0"
transformers = "*"