[project]
name = "MAX notebooks"
version = "1.0.0"
description = "MAX Examples"
authors = ["Modular <hello@modular.com>"]
channels = ["pytorch", "conda-forge", "anaconda", "https://conda.modular.com/max/"]
platforms = ["osx-arm64","linux-64"]

[dependencies]
python = ">=3.11,<3.12"
max = ">=24.4.0dev6"
jupyterlab = ">=4.2.3,<4.3"
nb_conda_kernels = "*"
ipykernel = ">=6.29.5,<6.30"