[project]
name = "BERT Mojo Torchscript"
version = "1.0.0"
description = "MAX Examples"
authors = ["Modular <hello@modular.com>"]
channels = ["pytorch", "conda-forge", "anaconda", "https://conda.modular.com/max/"]
platforms = ["osx-arm64","linux-64","linux-aarch64"]

[dependencies]
python = ">=3.11,<3.12"
max = ">=24.4.0dev6"
pip = ">=24.0,<25"
pytorch = "~=2.2.2"
transformers = "*"
numpy = "<2.0.0"